export enum Permission {
  CREATE_RESOURCE = 'CREATE_RESOURCE',
  UPDATE_RESOURCE = 'UPDATE_RESOURCE',
  DELETE_RESOURCE = 'DELETE_RESOURCE',
  VIEW_RESOURCE = 'VIEW_RESOURCE',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
}
